---
-
  name: Install and configure rclone
  block:
    - name: Download rclone
      ansible.windows.win_get_url:
        url: '{{ rclone_url }}'
        dest: '%TEMP%\\rclone.zip'

    - name: Unarchive rclone zip
      community.windows.win_unzip:
        src: '%TEMP%\\rclone.zip'
        dest: '%TEMP%\\rclone'

    - name: Create C:\bin directory
      ansible.windows.win_file:
        path: C:\\bin
        state: directory

    - name: Get extracted directory name
      ansible.windows.win_find:
        paths: '{{ ansible_env.TEMP }}\\rclone'
        file_type: directory
      register: rclone_extracted_dir

    - name: Move extracted directory to C:\bin
      ansible.windows.win_powershell:
        script: |
          Move-Item -Path "{{ rclone_extracted_dir.files[0].path }}" -Destination "{{ rclone_dir_path }}" -Force

    - name:  Copy rclone config
      ansible.windows.win_template:
        src: template/rclone-host-onprem-conf.j2
        dest: '{{ rclone_config_path }}'

    - name: Apply configuration
      ansible.windows.win_environment:
        name: RCLONE_CONFIG
        value: '{{ rclone_config_path }}'
        level: machine
        state: present
        
    - name: Add rclone to the PATH
      ansible.windows.win_path:
        elements: '{{ rclone_dir_path }}'

    - name: Create logs directory
      ansible.windows.win_file:
        path: '{{ rclone_dir_path }}\\logs'
        state: directory

-
  name: Create a task to run rclone
  block:
    - name: Create a task to pull data from on-prem
      community.windows.win_scheduled_task:
        name: rclone-pull
        description: "Rclone sync task to pull data from on-prem"
        actions:
          - path: rclone.exe
            arguments: "sync host_onprem_src: host_cloud_dest: --log-file={{ onprem_to_cloud_log }} --log-level {{ log_level }}"
        triggers:
          - type: time
            start_boundary: '2023-10-01T00:00:00'
            enabled: yes
            repetition:
              interval: 'PT5M'
              stop_at_duration_end: false
        multiple_instances: 2

    - name: Create a task to push data to on-prem
      community.windows.win_scheduled_task:
        name: rclone-push
        description: "Rclone sync task to push data to on-prem"
        actions: 
          - path: rclone.exe 
            arguments: "sync host_cloud_src: host_onprem_dest: --log-file={{ cloud_to_onprem_log }} --log-level {{ log_level }}"
        triggers:
          - type: time
            start_boundary: '2023-10-01T00:00:00'
            enabled: yes
            repetition:
              interval: 'PT5M'
              stop_at_duration_end: false
        multiple_instances: 2
